version: "3.8"

services:
  static:
    container_name: welcome
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8089:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.welcome.entrypoints=websecure"
      - "traefik.http.routers.welcome.rule=Host(`yourdomain.com`) && PathPrefix(`/welcome`)"
      - "traefik.http.middlewares.welcome-stripprefix.stripprefix.prefixes=/welcome"
      - "traefik.http.routers.welcome.middlewares=trailing-slash@file,welcome-stripprefix@docker"

networks:
  proxy:
    external: true