name: welcome

services:
  static:
    container_name: welcome
    image: ghcr.io/fritzip/welcome-to:latest
    env_file: .env
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.welcome.entrypoints=websecure"
      - "traefik.http.routers.welcome.rule=Host(`${DOMAIN}`) && PathPrefix(`/${PATH_PREFIX}`)"
      - "traefik.http.middlewares.welcome-stripprefix.stripprefix.prefixes=/${PATH_PREFIX}"
      - "traefik.http.routers.welcome.middlewares=trailing-slash@file,welcome-stripprefix@docker"
      - "traefik.http.services.welcome.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
