name: welcome

services:
  static:
    container_name: welcome
    image: nginx
    env_file: .env
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.welcome.entrypoints=websecure"
      - "traefik.http.routers.welcome.rule=Host(`${DOMAIN}`) && PathPrefix(`/${PATH_PREFIX}`)"
      - "traefik.http.middlewares.welcome-stripprefix.stripprefix.prefixes=/${PATH_PREFIX}"
      - "traefik.http.routers.welcome.middlewares=trailing-slash@file,welcome-stripprefix@docker"

networks:
  proxy:
    external: true
